version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: daily
      time: "11:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: chore
      include: scope
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
      time: "11:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: chore
      include: scope
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "11:00"
    open-pull-requests-limit: 5
    versioning-strategy: increase
    commit-message:
      prefix: chore
      include: scope
