# Use [REST Client](https://marketplace.visualstudio.com/items?itemName=humao.rest-client) to run these requests

@base=http://localhost:5000
# @base=https://apis.fromdoppler.com/conversion-tool
# @base=https://apisint.fromdoppler.net/conversion-tool
# @base=https://apisqa.fromdoppler.net/conversion-tool

# Set api key token here
@Token=

###
GET {{base}}/swagger/index.html

###
GET {{base}}/version.txt

###
GET {{base}}/hello/anonymous

###
GET {{base}}/hello/valid-token
Authorization: Bearer {{Token}}

###
GET {{base}}/hello/superuser
Authorization: Bearer {{Token}}

###
GET {{base}}/accounts/123/hello
Authorization: Bearer {{Token}}

###
GET {{base}}/accounts/test1@test.com/hello
Authorization: Bearer {{Token}}

###
POST {{base}}/html-to-image/png
Authorization: Bearer {{Token}}
Content-Type: application/json

{
   "Html": "<h1>Title</h1><p>this is a paragraph text</p>"
}
