name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  continuous-delivery:
    name: Continuous Integration and Delivery
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Install wkhtmltopdf
        run: sudo apt-get install xvfb libfontconfig wkhtmltopdf
      - name: Verify code format
        run: dotnet format --verify-no-changes
      - name: Build with dotnet
        run: dotnet build --configuration Release
      - name: Test with dotnet
        run: dotnet test --no-build --configuration Release --collect:"XPlat Code Coverage"
      - uses: codecov/codecov-action@v3.1.1

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.10.2
        with:
          versionSpec: "5.x"
      - name: Determine Version
        id: version # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v0.10.2
      - name: Pack nuget
        run: |
          dotnet pack \
            --output ./nugets \
            --configuration Release \
            -p:Version=${{ steps.version.outputs.nuGetVersion }}
      - name: Check if generates nugets packages
        id: has-nugets
        uses: andstor/file-existence-action@v1
        with:
          files: "./nugets/*.nupkg"
      - name: Upload artifact
        if: steps.has-nugets.outputs.files_exists == 'true'
        uses: actions/upload-artifact@v3.1.2
        with:
          name: nugets
          path: ./nugets/*.nupkg
      - name: Delivery nuget to Github Packages
        if: steps.has-nugets.outputs.files_exists == 'true'
        run: |
          dotnet nuget push ./nugets/*.nupkg \
            --skip-duplicate \
            --api-key ${{ secrets.GITHUB_TOKEN }} \
            --source 'https://nuget.pkg.github.com/${{ github.REPOSITORY_OWNER }}/index.json'
